### ISSUE TITLE
include PekkoDependency class so it can be shared among Pekko projects

### ISSUE THREAD

**Issue by pjfanning** [mdedetrich/sbt-apache-sonatype#25]
https://github.com/apache/incubator-pekko-http/blob/main/project/PekkoDependency.scala

Slightly out of date copies of this are already used in some other repos
* incubator-pekko-management
* incubator-pekko-persistence-dynamodb

**Comment by mdedetrich** [comment]
So this project is actually deliberately designed not to be specific to Pekko, instead its been solved with https://github.com/pjfanning/sbt-pekko-build so I am going to close this issue.

If there is a misunderstanding then let me know and I will re-open.
